"""Paquete fuente ADY1100 Bank Marketing — API pública deliberada."""

from .cleaning import (
    cap_outliers_iqr,
    detect_outliers_iqr,
    drop_leakage_columns,
    impute_categorical_mode,
    impute_pdays_clean_median,
    replace_unknown_with_nan,
    transform_pdays,
)
from .load_data import (
    get_outputs_dir,
    get_processed_dir,
    get_project_root,
    get_raw_data_path,
    load_bank_data,
)
from .transform import encode_target, one_hot_encode, scale_numeric_columns
from .validation import (
    UNKNOWN_TOKEN,
    EXPECTED_COLUMNS,
    calcular_checksum_md5,
    compute_md5_checksum,
    count_unknown_values,
    get_basic_summary,
    validate_columns,
)
from .visualization import (
    plot_barplot_rate,
    plot_boxplot_bivariate,
    plot_correlation_heatmap,
    plot_countplot,
    plot_histogram_kde,
    plot_macro_trends,
    plot_numeric_boxplots,
    plot_pie_distribution,
    plot_scatter_with_hue,
    plot_target_distribution,
    plot_violin,
)

__all__ = [
    "EXPECTED_COLUMNS",
    "UNKNOWN_TOKEN",
    "calcular_checksum_md5",
    "cap_outliers_iqr",
    "compute_md5_checksum",
    "count_unknown_values",
    "detect_outliers_iqr",
    "drop_leakage_columns",
    "encode_target",
    "get_basic_summary",
    "get_outputs_dir",
    "get_processed_dir",
    "get_project_root",
    "get_raw_data_path",
    "impute_categorical_mode",
    "impute_pdays_clean_median",
    "load_bank_data",
    "one_hot_encode",
    "plot_barplot_rate",
    "plot_boxplot_bivariate",
    "plot_correlation_heatmap",
    "plot_countplot",
    "plot_histogram_kde",
    "plot_macro_trends",
    "plot_numeric_boxplots",
    "plot_pie_distribution",
    "plot_scatter_with_hue",
    "plot_target_distribution",
    "plot_violin",
    "replace_unknown_with_nan",
    "scale_numeric_columns",
    "transform_pdays",
    "validate_columns",
]
